#!/usr/bin/env bash

set -eu
trap "exit 1" INT

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    AGAINST=HEAD
else
    # Initial commit: diff against an empty tree object
    AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached "$AGAINST" --

GIT_ROOT="$(git rev-parse --show-toplevel)"

set -x
"$GIT_ROOT/lint.sh"
