#!/usr/bin/env bash

## Copy names of all changed files in a git repo.

set -eo pipefail

if [[ $# -gt 1 || ${1-0} -lt 0 ]]; then
    echo "$0"
    echo
    echo "Copy names of all changed files in a git repo."
    exit 1
fi

CURRENT_DIR="$PWD"

mapfile -d "" -t FILES < <(
    git status --porcelain |
        sed -n "/^.[^ ]/ p" | # Skip staged changes
        sed -E "s/^RM .+ -> (.+)$/M  \1/" | # Treat renames same as modifications
        cut -c 4- |
        (
            cd "$(git rev-parse --show-toplevel)"
            gxargs --delimiter="\n" realpath -z --relative-to "$CURRENT_DIR"
        )
)

printf "%q " "${FILES[@]}" | cb
echo "Copied ${#FILES[@]} file names."
