#!/usr/bin/env bash

set -eo pipefail

if [[ $# -ne 0 ]]; then
    echo "$0"
    echo
    echo "Copy name of first modified file in git repo, or first untracked"
    echo "file if no such file exists."
    exit 1
fi

FILE="$( ( git ls-files -m; git ls-files -o ) | head -n 1 | tr -d '\n' )"
if [[ -n $FILE ]]; then
    pbcopy <<< "$FILE"
    echo "Copied \"$FILE\""
else
    echo "No such file."
fi
