#!/usr/bin/env bash

## Copy particular file from output of git-status to clipboard.

set -eo pipefail

if [[ $# -gt 1 || ! ${1-0} =~ ^[0-9]+|-?i$ ]]; then
    echo "$0" [SKIP_N=0]
    echo "$0" "i|-i"
    echo
    echo "Looks at the list of files displayed by git-status and"
    echo "after skipping staged changes and then the first SKIP_N entries"
    echo "after that, will copy the top file to your clipboard."
    echo
    echo "Give i or -i instead of a number for an interactive prompt to choose"
    echo "the file."
    exit 1
fi

SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P )"
CURRENT_DIR="$PWD"

mapfile -t PATHS < <(
    git status --porcelain |
        sed -n "/^.[^ ]/ p" | # Skip staged changes
        sed -E "s/^RM .+ -> (.+)$/M  \1/" | # Treat renames same as modifications
        cut -c 4- |
        (
            cd "$(git rev-parse --show-toplevel)" &&
            xargs realpath --relative-to="$CURRENT_DIR"
        )
)

SELECTED_INDEX="${1-0}"
if [[ $# -eq 1 && ${1-0} =~ ^-?i$ ]]; then
    declare -i INDEX=0
    for i in "${PATHS[@]}"; do
        printf "  %d. %s\n" "$INDEX" "$i"
        INDEX=$((INDEX + 1))
    done
    printf "Choose which path to copy: "
    read -r SELECTED_INDEX
fi

if [[ ! $SELECTED_INDEX =~ ^[0-9]+$ || $SELECTED_INDEX -lt 0 || $SELECTED_INDEX -ge ${#PATHS[@]} ]]; then
    echo "Invalid index."
    exit 1
fi

FILE="${PATHS[$SELECTED_INDEX]}"

if [[ -n $FILE ]]; then
    "$SCRIPT_DIR/cb" <<< "$FILE"
    echo "Copied \"$FILE\""
else
    echo "No such file."
fi
