#!/usr/bin/env bash

## Convert heic files to jpg files.

if [[ $# -eq 0 || ( $# == 1 && ( $1 == -h || $1 == --help ) ) ]]; then
    echo "$0 FILE [FILE...]"
    echo
    echo "Converts given .heic files to .jpg files."
    exit 1
fi

for i in "$@"; do
    if grep -E --quiet -i '^.+\.heic$' <<< "$i"; then
        # shellcheck disable=SC2001
        sips -s format jpeg "$i" --out "$(sed 's/.heic$/.jpg/i' <<< "$i")"
    else
        echo "$i doesn't end with '.heic'. Ignoring."
    fi
done
