#!/usr/bin/env bash

## Serve current directory over HTTP.

set -ue

function contains {
    for i in "${@:2}"; do
        if [[ $i == "$1" ]]; then
            return 0
        fi
    done

    return 1
}

if contains --port "$@"; then
    set -x
    npx live-server "$@"
else
    set -x
    npx live-server --port=2282 "$@"
fi
