alias d="cd"
alias s="ls"

alias ga="git add"
alias gb="git branch"
alias gc="git checkout"
alias gcp="git cherry-pick"
alias gd="git diff"
alias gdc="git diff --cached"
alias gf="git fetch"
alias gg="git grep"
alias gl="git log"
alias gm="git commit"
alias gr="git reset"
alias gs="git status"
alias gsh="git show"
alias mk="cowsay 'Hi! I love you 💞' && clear"
alias pre="open -a Preview.app"
