alias d="cd"
alias s="ls"

alias ga="git add"
alias gc="git checkout"
alias gd="git diff"
alias gdc="git diff --cached"
alias gg="git grep --untracked --line-number"
alias gl="git log"
alias gm="git commit"
alias gr="git reset"
alias gs="git status"
alias gsh="git show"
alias mk="cowsay 'Hi! I love you 💞' && clear"
alias pre="open -a Preview.app"
